"""
exporter.py — Export optimized rule sets and audit reports in multiple formats.

Supported export formats:
  - iptables-save  (.iptables)  — Drop-in replacement for iptables-restore
  - JSON           (.json)      — Machine-readable structured output
  - YAML           (.yaml)      — Human-readable structured output
  - Markdown       (.md)        — Full audit report for sharing / documentation
  - CSV            (.csv)       — Flat recommendation list for spreadsheet review

Usage:
    from exporter import Exporter
    from recommendation_engine import RecommendationEngine

    exporter = Exporter()

    # Export optimized rules
    exporter.to_iptables(optimized_rules, "output/optimized.iptables")
    exporter.to_json(optimized_rules, recommendations, "output/audit.json")
    exporter.to_markdown(rules, recommendations, conflict_report, "output/audit.md")

    # Or export everything at once
    exporter.export_all("output/", rules, optimized_rules, recommendations,
                        conflict_report, opt_result)
"""

from __future__ import annotations

import json
import csv
from datetime import datetime
from pathlib import Path
from typing import Optional

from parser.models import Action, FirewallRule, Protocol
from engine.conflict_engine import ConflictReport, Severity
from recommendation_engine import Recommendation
from ml.rule_optimizer import OptimizationResult


class Exporter:
    """Multi-format exporter for rules and audit reports."""

    # ─────────────────────────────────────────────── iptables

    def to_iptables(
        self,
        rules:     list[FirewallRule],
        filepath:  str,
        table:     str = "filter",
        chain:     str = "INPUT",
        policy:    str = "DROP",
    ) -> str:
        """
        Export rules to iptables-save format.
        Returns the generated text (also writes to filepath if provided).
        """
        lines = [
            f"# Generated by Firewall Rule Optimizer",
            f"# Date: {datetime.now().isoformat()}",
            f"# Rules: {len(rules)}",
            f"*{table}",
            f":{chain} {policy} [0:0]",
            f":FORWARD DROP [0:0]",
            f":OUTPUT ACCEPT [0:0]",
            "",
        ]

        for rule in sorted(rules, key=lambda r: r.priority):
            line = self._rule_to_iptables(rule, chain)
            if line:
                if rule.comment:
                    lines.append(f"# {rule.comment}")
                lines.append(line)

        lines.append("")
        lines.append("COMMIT")

        text = "\n".join(lines)
        if filepath:
            Path(filepath).parent.mkdir(parents=True, exist_ok=True)
            Path(filepath).write_text(text)
        return text

    def _rule_to_iptables(self, rule: FirewallRule, default_chain: str) -> Optional[str]:
        """Convert a single FirewallRule to an iptables-save line."""
        chain = rule.chain or default_chain

        parts = [f"-A {chain}"]

        # Source IP
        if rule.src_ip and rule.src_ip not in ("0.0.0.0/0", "::/0"):
            parts.append(f"-s {rule.src_ip}")

        # Destination IP
        if rule.dst_ip and rule.dst_ip not in ("0.0.0.0/0", "::/0"):
            parts.append(f"-d {rule.dst_ip}")

        # Protocol
        if rule.protocol != Protocol.ALL:
            parts.append(f"-p {rule.protocol.value}")

        # Interface
        if rule.interface:
            parts.append(f"-i {rule.interface}")

        # Source port
        if rule.src_port:
            parts.append(f"--sport {rule.src_port.replace(':', ':')}")

        # Destination port
        if rule.dst_port:
            parts.append(f"--dport {rule.dst_port.replace(':', ':')}")

        # Action / jump target
        action_map = {
            Action.ALLOW:  "ACCEPT",
            Action.DENY:   "DROP",
            Action.DROP:   "DROP",
            Action.REJECT: "REJECT",
            Action.LOG:    "LOG",
        }
        jump = action_map.get(rule.action, "DROP")
        parts.append(f"-j {jump}")

        return " ".join(parts)

    # ─────────────────────────────────────────────── JSON

    def to_json(
        self,
        rules:           list[FirewallRule],
        recommendations: list[Recommendation],
        filepath:        str,
        conflict_report: Optional[ConflictReport] = None,
        opt_result:      Optional[OptimizationResult] = None,
        pretty:          bool = True,
    ) -> str:
        """Export full audit as a structured JSON document."""
        doc = {
            "generated_at": datetime.now().isoformat(),
            "summary": {
                "total_rules":       len(rules),
                "total_recommendations": len(recommendations),
                "critical_count":    sum(1 for r in recommendations
                                         if r.severity == Severity.CRITICAL),
                "high_count":        sum(1 for r in recommendations
                                         if r.severity == Severity.HIGH),
            },
            "rules": [r.to_dict() for r in sorted(rules, key=lambda x: x.priority)],
            "recommendations": [r.to_dict() for r in recommendations],
        }

        if conflict_report:
            doc["conflict_report"] = conflict_report.to_dict()

        if opt_result:
            doc["optimization"] = opt_result.to_dict()

        text = json.dumps(doc, indent=2 if pretty else None, default=str)
        if filepath:
            Path(filepath).parent.mkdir(parents=True, exist_ok=True)
            Path(filepath).write_text(text)
        return text

    # ─────────────────────────────────────────────── YAML

    def to_yaml(
        self,
        rules:           list[FirewallRule],
        recommendations: list[Recommendation],
        filepath:        str,
    ) -> str:
        """Export as YAML (human-readable, no PyYAML dependency — hand-crafted)."""

        def val(v) -> str:
            if v is None:
                return "~"
            if isinstance(v, bool):
                return str(v).lower()
            if isinstance(v, (int, float)):
                return str(v)
            s = str(v)
            if any(c in s for c in (':', '#', '[', ']', '{', '}', '!', '|', '>', '&', '*')):
                return f'"{s}"'
            return s

        lines = [
            "---",
            f"generated_at: {datetime.now().isoformat()}",
            "",
            "summary:",
            f"  total_rules: {len(rules)}",
            f"  total_recommendations: {len(recommendations)}",
            "",
            "rules:",
        ]

        for rule in sorted(rules, key=lambda r: r.priority):
            lines += [
                f"  - rule_id: {val(rule.rule_id)}",
                f"    priority: {rule.priority}",
                f"    src_ip: {val(rule.src_ip)}",
                f"    dst_ip: {val(rule.dst_ip)}",
                f"    dst_port: {val(rule.dst_port)}",
                f"    protocol: {val(rule.protocol.value)}",
                f"    action: {val(rule.action.value)}",
                f"    comment: {val(rule.comment)}",
            ]

        lines += ["", "recommendations:"]
        for rec in recommendations:
            lines += [
                f"  - rec_id: {val(rec.rec_id)}",
                f"    severity: {val(rec.severity.value)}",
                f"    fix_type: {val(rec.fix_type.value)}",
                f"    effort: {val(rec.effort.value)}",
                f"    impact_score: {round(rec.impact_score, 2)}",
                f"    title: {val(rec.title)}",
                f"    affected_rules: {rec.affected_rules}",
            ]

        text = "\n".join(lines) + "\n"
        if filepath:
            Path(filepath).parent.mkdir(parents=True, exist_ok=True)
            Path(filepath).write_text(text)
        return text

    # ─────────────────────────────────────────────── Markdown

    def to_markdown(
        self,
        original_rules:  list[FirewallRule],
        optimized_rules: list[FirewallRule],
        recommendations: list[Recommendation],
        conflict_report: ConflictReport,
        opt_result:      Optional[OptimizationResult],
        filepath:        str,
    ) -> str:
        """Generate a comprehensive Markdown audit report."""
        now = datetime.now().strftime("%Y-%m-%d %H:%M")

        # Severity emoji map
        sev_icon = {
            Severity.CRITICAL: "🔴",
            Severity.HIGH:     "🟠",
            Severity.MEDIUM:   "🟡",
            Severity.LOW:      "🟢",
        }

        critical = [r for r in recommendations if r.severity == Severity.CRITICAL]
        high     = [r for r in recommendations if r.severity == Severity.HIGH]
        medium   = [r for r in recommendations if r.severity == Severity.MEDIUM]
        low      = [r for r in recommendations if r.severity == Severity.LOW]

        sections = []

        # ── Header ────────────────────────────────────────────────────────────
        sections.append(f"""# Firewall Rule Audit Report
Generated: {now}

---

## Executive Summary

| Metric | Value |
|---|---|
| Total rules analyzed | {conflict_report.total_rules} |
| Total recommendations | {len(recommendations)} |
| 🔴 Critical | {len(critical)} |
| 🟠 High | {len(high)} |
| 🟡 Medium | {len(medium)} |
| 🟢 Low | {len(low)} |
| Contradictions found | {conflict_report.contradiction_count} |
| Shadowed rules | {conflict_report.shadow_count} |
| Duplicate rules | {conflict_report.duplicate_count} |
| Permissive rules | {conflict_report.permissive_count} |
""")

        # ── ML Optimization summary (if available) ────────────────────────────
        if opt_result:
            sections.append(f"""## ML Optimization Results

| Metric | Value |
|---|---|
| Rules reordered | {opt_result.rules_moved} |
| Estimated speedup | {opt_result.estimated_speedup:.2f}x |
| Policy equivalent | {"✅ Yes" if opt_result.policy_equivalent else "❌ No"} |
| Model R² | {opt_result.metrics.cv_r2_mean:.3f} ± {opt_result.metrics.cv_r2_std:.3f} |

### Top 5 Feature Importances

| Feature | Importance |
|---|---|
""")
            top_features = sorted(
                opt_result.metrics.feature_importances.items(),
                key=lambda x: -x[1]
            )[:5]
            feat_rows = "\n".join(
                f"| `{name}` | {score:.4f} |"
                for name, score in top_features
            )
            sections[-1] += feat_rows + "\n"

        # ── Recommendations ───────────────────────────────────────────────────
        sections.append("## Recommendations\n")

        for rec in recommendations:
            icon = sev_icon.get(rec.severity, "⚪")
            sections.append(f"""### {icon} {rec.rec_id}: {rec.title}

| Field | Value |
|---|---|
| Severity | {rec.severity.value} |
| Fix type | {rec.fix_type.value} |
| Effort | {rec.effort.value} |
| Impact score | {rec.impact_score:.1f} / 10.0 |
| Affected rules | {", ".join(f"`{r}`" for r in rec.affected_rules) or "—"} |

**Description:** {rec.description}

**Suggestion:** {rec.suggestion}

---
""")

        # ── Current rule set table ────────────────────────────────────────────
        sections.append("## Current Rule Set\n")
        sections.append("| Priority | Rule ID | Src IP | Dst IP | Port | Protocol | Action | Comment |")
        sections.append("|---|---|---|---|---|---|---|---|")
        for rule in sorted(original_rules, key=lambda r: r.priority):
            sections.append(
                f"| {rule.priority} "
                f"| `{rule.rule_id}` "
                f"| {rule.src_ip} "
                f"| {rule.dst_ip} "
                f"| {rule.dst_port or 'any'} "
                f"| {rule.protocol.value} "
                f"| {rule.action.value} "
                f"| {rule.comment or '—'} |"
            )

        # ── Optimized rule set table ──────────────────────────────────────────
        if optimized_rules and optimized_rules != original_rules:
            sections.append("\n## Optimized Rule Order\n")
            sections.append("| New Priority | Rule ID | Old Priority | Delta |")
            sections.append("|---|---|---|---|")
            orig_prio = {r.rule_id: r.priority for r in original_rules}
            for rule in optimized_rules:
                old_p = orig_prio.get(rule.rule_id, "?")
                delta = (old_p - rule.priority) if isinstance(old_p, int) else "?"
                delta_str = f"+{delta}" if isinstance(delta, int) and delta > 0 else str(delta)
                sections.append(
                    f"| {rule.priority} | `{rule.rule_id}` | {old_p} | {delta_str} |"
                )

        sections.append("\n---\n*Report generated by AI-Powered Firewall Rule Optimizer*\n")

        text = "\n".join(sections)
        if filepath:
            Path(filepath).parent.mkdir(parents=True, exist_ok=True)
            Path(filepath).write_text(text)
        return text

    # ─────────────────────────────────────────────── CSV

    def to_csv(
        self,
        recommendations: list[Recommendation],
        filepath:        str,
    ) -> str:
        """Export recommendations as a flat CSV for spreadsheet review."""
        rows = []
        for rec in recommendations:
            rows.append({
                "rec_id":          rec.rec_id,
                "severity":        rec.severity.value,
                "fix_type":        rec.fix_type.value,
                "effort":          rec.effort.value,
                "impact_score":    round(rec.impact_score, 2),
                "title":           rec.title,
                "affected_rules":  "|".join(rec.affected_rules),
                "source_findings": "|".join(rec.source_findings),
                "suggestion":      rec.suggestion,
            })

        lines = []
        if rows:
            writer_output = []
            import io
            buf = io.StringIO()
            writer = csv.DictWriter(buf, fieldnames=list(rows[0].keys()))
            writer.writeheader()
            writer.writerows(rows)
            text = buf.getvalue()
        else:
            text = "rec_id,severity,fix_type,effort,impact_score,title,affected_rules,source_findings,suggestion\n"

        if filepath:
            Path(filepath).parent.mkdir(parents=True, exist_ok=True)
            Path(filepath).write_text(text)
        return text

    # ─────────────────────────────────────────────── export_all

    def export_all(
        self,
        output_dir:      str,
        original_rules:  list[FirewallRule],
        optimized_rules: list[FirewallRule],
        recommendations: list[Recommendation],
        conflict_report: ConflictReport,
        opt_result:      Optional[OptimizationResult] = None,
    ) -> dict[str, str]:
        """
        Export all formats to output_dir.
        Returns a dict mapping format name → filepath.
        """
        out = Path(output_dir)
        out.mkdir(parents=True, exist_ok=True)

        paths = {}

        paths["iptables_original"] = str(out / "original.iptables")
        self.to_iptables(original_rules, paths["iptables_original"])

        paths["iptables_optimized"] = str(out / "optimized.iptables")
        self.to_iptables(optimized_rules, paths["iptables_optimized"])

        paths["json"] = str(out / "audit.json")
        self.to_json(optimized_rules, recommendations, paths["json"],
                     conflict_report, opt_result)

        paths["yaml"] = str(out / "audit.yaml")
        self.to_yaml(optimized_rules, recommendations, paths["yaml"])

        paths["markdown"] = str(out / "audit_report.md")
        self.to_markdown(original_rules, optimized_rules, recommendations,
                         conflict_report, opt_result, paths["markdown"])

        paths["csv"] = str(out / "recommendations.csv")
        self.to_csv(recommendations, paths["csv"])

        return paths