"""
test_parsers.py — Unit tests for all four firewall rule parsers.

Run with:
    pytest tests/test_parsers.py -v
"""

import json
import pytest
from parser.models import Action, FirewallRule, Protocol
from parser.iptables_parser import IptablesParser
from parser.json_csv_parser import JsonCsvParser
from parser.cisco_acl_parser import CiscoACLParser
from parser.aws_sg_parser import AWSSGParser


# ═══════════════════════════════════════════════════════════════════════════════
# Sample inputs
# ═══════════════════════════════════════════════════════════════════════════════

IPTABLES_SAMPLE = """
# Generated by iptables-save
*filter
:INPUT   DROP  [0:0]
:FORWARD DROP  [0:0]
:OUTPUT  ACCEPT [0:0]

# Allow established connections
-A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT

# Allow SSH from management subnet
-A INPUT -s 10.10.10.0/24 -p tcp --dport 22 -j ACCEPT -m comment --comment "mgmt-ssh"

# Allow HTTP and HTTPS from anywhere
-A INPUT -p tcp --dport 80  -j ACCEPT
-A INPUT -p tcp --dport 443 -j ACCEPT

# Allow DNS outbound
-A OUTPUT -p udp --dport 53 -j ACCEPT

# Drop everything else inbound
-A INPUT -j DROP

COMMIT
"""

JSON_SAMPLE = json.dumps([
    {
        "priority": 10,
        "src_ip":   "192.168.1.0/24",
        "dst_ip":   "0.0.0.0/0",
        "dst_port": "443",
        "protocol": "tcp",
        "action":   "ALLOW",
        "comment":  "Allow HTTPS from LAN"
    },
    {
        "priority": 20,
        "src_ip":   "0.0.0.0/0",
        "dst_ip":   "10.0.0.0/8",
        "dst_port": "22",
        "protocol": "tcp",
        "action":   "deny",
        "comment":  "Block SSH to private range"
    },
    {
        "priority": 30,
        "protocol": "all",
        "action":   "ALLOW",
    },
])

CSV_SAMPLE = """\
priority,src_ip,dst_ip,src_port,dst_port,protocol,action,comment
10,192.168.1.0/24,0.0.0.0/0,,443,tcp,ALLOW,LAN to HTTPS
20,10.0.0.0/8,172.16.0.0/12,,80,tcp,ALLOW,Internal HTTP
30,0.0.0.0/0,0.0.0.0/0,,,all,DENY,Default deny
"""

CISCO_ACL_SAMPLE = """\
ip access-list extended OUTSIDE_IN
 remark Allow public HTTP
 permit tcp any any eq 80
 remark Allow public HTTPS
 permit tcp any any eq 443
 permit udp host 8.8.8.8 any eq 53
 permit tcp 192.168.0.0 0.0.255.255 any range 1024 65535
 deny   ip any any log

ip access-list standard RFC1918_BLOCK
 deny   10.0.0.0 0.255.255.255
 deny   172.16.0.0 0.15.255.255
 deny   192.168.0.0 0.0.255.255
 permit any

access-list 101 permit tcp 10.0.0.0 0.255.255.255 any eq 443
access-list 101 deny   ip any any
"""

AWS_SG_SAMPLE = {
    "SecurityGroups": [
        {
            "GroupId":     "sg-0abc123",
            "GroupName":   "web-servers",
            "Description": "Public web tier",
            "IpPermissions": [
                {
                    "IpProtocol": "tcp",
                    "FromPort":   80,
                    "ToPort":     80,
                    "IpRanges": [
                        {"CidrIp": "0.0.0.0/0", "Description": "Public HTTP"}
                    ],
                    "Ipv6Ranges": [],
                    "UserIdGroupPairs": []
                },
                {
                    "IpProtocol": "tcp",
                    "FromPort":   443,
                    "ToPort":     443,
                    "IpRanges": [
                        {"CidrIp": "0.0.0.0/0", "Description": "Public HTTPS"},
                        {"CidrIp": "10.0.0.0/8", "Description": "Internal HTTPS"},
                    ],
                    "Ipv6Ranges": [{"CidrIpv6": "::/0"}],
                    "UserIdGroupPairs": []
                },
                {
                    "IpProtocol": "tcp",
                    "FromPort":   3306,
                    "ToPort":     3306,
                    "IpRanges": [],
                    "Ipv6Ranges": [],
                    "UserIdGroupPairs": [{"GroupId": "sg-0db456"}]
                },
            ],
            "IpPermissionsEgress": [
                {
                    "IpProtocol": "-1",
                    "IpRanges":   [{"CidrIp": "0.0.0.0/0"}],
                    "Ipv6Ranges": [],
                    "UserIdGroupPairs": []
                }
            ]
        }
    ]
}


# ═══════════════════════════════════════════════════════════════════════════════
# iptables tests
# ═══════════════════════════════════════════════════════════════════════════════

class TestIptablesParser:

    def setup_method(self):
        self.parser = IptablesParser()
        self.rules  = self.parser.parse_text(IPTABLES_SAMPLE)

    def test_parse_returns_list_of_firewall_rules(self):
        assert all(isinstance(r, FirewallRule) for r in self.rules)

    def test_correct_rule_count(self):
        # 6 -A lines with recognised targets (ESTABLISHED rule + SSH + HTTP + HTTPS + DNS + DROP)
        assert len(self.rules) == 6

    def test_ssh_rule_src_ip(self):
        ssh = next(r for r in self.rules if r.dst_port == "22")
        assert ssh.src_ip == "10.10.10.0/24"

    def test_ssh_rule_action(self):
        ssh = next(r for r in self.rules if r.dst_port == "22")
        assert ssh.action == Action.ALLOW

    def test_ssh_rule_comment(self):
        ssh = next(r for r in self.rules if r.dst_port == "22")
        assert ssh.comment == "mgmt-ssh"

    def test_http_rule_protocol(self):
        http = next(r for r in self.rules if r.dst_port == "80")
        assert http.protocol == Protocol.TCP

    def test_drop_rule_has_no_src_port(self):
        drop = next(r for r in self.rules if r.action == Action.DROP)
        assert drop.src_port is None

    def test_dns_rule_is_udp(self):
        dns = next(r for r in self.rules if r.dst_port == "53")
        assert dns.protocol == Protocol.UDP

    def test_source_field(self):
        assert all(r.source == "iptables" for r in self.rules)

    def test_priorities_are_sequential(self):
        priorities = [r.priority for r in self.rules]
        assert priorities == sorted(priorities)

    def test_skip_comments_and_table_headers(self):
        # No rule should have raw starting with # or *
        for r in self.rules:
            assert not (r.raw or "").startswith("#")
            assert not (r.raw or "").startswith("*")


# ═══════════════════════════════════════════════════════════════════════════════
# JSON / CSV tests
# ═══════════════════════════════════════════════════════════════════════════════

class TestJsonParser:

    def setup_method(self):
        self.rules = JsonCsvParser().parse_json(JSON_SAMPLE)

    def test_rule_count(self):
        assert len(self.rules) == 3

    def test_first_rule_action_allow(self):
        assert self.rules[0].action == Action.ALLOW

    def test_second_rule_action_deny(self):
        assert self.rules[1].action == Action.DENY

    def test_priority_respected(self):
        assert self.rules[0].priority == 10
        assert self.rules[1].priority == 20

    def test_cidr_preserved(self):
        assert self.rules[0].src_ip == "192.168.1.0/24"

    def test_missing_optional_fields_default(self):
        # Rule 3 has no src_ip / dst_ip
        assert self.rules[2].src_ip == "0.0.0.0/0"
        assert self.rules[2].dst_ip == "0.0.0.0/0"

    def test_protocol_all(self):
        assert self.rules[2].protocol == Protocol.ALL

    def test_case_insensitive_action(self):
        assert self.rules[1].action == Action.DENY  # input was lowercase "deny"


class TestCsvParser:

    def setup_method(self):
        self.rules = JsonCsvParser().parse_csv(CSV_SAMPLE)

    def test_rule_count(self):
        assert len(self.rules) == 3

    def test_default_deny_row(self):
        deny = next(r for r in self.rules if r.action == Action.DENY)
        assert deny.src_ip == "0.0.0.0/0"

    def test_lan_rule_dst_port(self):
        lan = next(r for r in self.rules if "LAN" in (r.comment or ""))
        assert lan.dst_port == "443"

    def test_all_rules_have_source(self):
        assert all(r.source == "json_csv" for r in self.rules)


# ═══════════════════════════════════════════════════════════════════════════════
# Cisco ACL tests
# ═══════════════════════════════════════════════════════════════════════════════

class TestCiscoACLParser:

    def setup_method(self):
        self.rules = CiscoACLParser().parse_text(CISCO_ACL_SAMPLE)

    def test_returns_firewall_rules(self):
        assert all(isinstance(r, FirewallRule) for r in self.rules)

    def test_extended_acl_http_rule(self):
        http = next(r for r in self.rules if r.dst_port == "80" and r.chain == "OUTSIDE_IN")
        assert http.action == Action.ALLOW
        assert http.protocol == Protocol.TCP
        assert http.src_ip == "0.0.0.0/0"

    def test_dns_host_src(self):
        dns = next(r for r in self.rules if r.dst_port == "53")
        assert dns.src_ip == "8.8.8.8/32"

    def test_range_port_parsing(self):
        range_rule = next(
            r for r in self.rules if r.dst_port and "1024" in r.dst_port
        )
        assert range_rule.dst_port == "1024:65535"

    def test_deny_all_is_logged(self):
        deny_all = next(
            r for r in self.rules if r.action == Action.DENY and r.chain == "OUTSIDE_IN"
        )
        assert "logged" in deny_all.tags

    def test_standard_acl_no_proto(self):
        rfc_rules = [r for r in self.rules if r.chain == "RFC1918_BLOCK"]
        assert len(rfc_rules) == 4  # 3 deny + 1 permit
        assert all(r.protocol == Protocol.ALL for r in rfc_rules)

    def test_wildcard_to_cidr_conversion(self):
        # 192.168.0.0 / 0.0.255.255 → 192.168.0.0/16
        cidr_rule = next(
            r for r in self.rules if r.src_ip == "192.168.0.0/16"
        )
        assert cidr_rule is not None

    def test_numbered_acl_parsed(self):
        num_rules = [r for r in self.rules if r.chain and r.chain.startswith("acl-101")]
        assert len(num_rules) == 2

    def test_remark_becomes_comment(self):
        http_rule = next(
            r for r in self.rules
            if r.dst_port == "80" and r.chain == "OUTSIDE_IN"
        )
        assert http_rule.comment == "Allow public HTTP"


# ═══════════════════════════════════════════════════════════════════════════════
# AWS Security Group tests
# ═══════════════════════════════════════════════════════════════════════════════

class TestAWSSGParser:

    def setup_method(self):
        self.rules = AWSSGParser().parse_dict(AWS_SG_SAMPLE)

    def test_returns_firewall_rules(self):
        assert all(isinstance(r, FirewallRule) for r in self.rules)

    def test_all_inbound_are_allow(self):
        inbound = [r for r in self.rules if r.chain == "inbound"]
        assert all(r.action == Action.ALLOW for r in inbound)

    def test_outbound_rule_exists(self):
        outbound = [r for r in self.rules if r.chain == "outbound"]
        assert len(outbound) >= 1

    def test_http_rule_src_ip(self):
        http = next(r for r in self.rules if r.dst_port == "80")
        assert http.src_ip == "0.0.0.0/0"

    def test_https_expands_to_two_ipv4_rules(self):
        https_ipv4 = [
            r for r in self.rules
            if r.dst_port == "443" and "ipv4" in r.tags and r.chain == "inbound"
        ]
        assert len(https_ipv4) == 2

    def test_ipv6_rule_tagged(self):
        ipv6 = [r for r in self.rules if "ipv6" in r.tags]
        assert len(ipv6) >= 1
        assert ipv6[0].src_ip == "::/0"

    def test_sg_reference_rule(self):
        sg_ref = next(r for r in self.rules if "sg-reference" in r.tags)
        assert "sg:sg-0db456" in sg_ref.src_ip

    def test_all_traffic_outbound_has_no_port(self):
        outbound = next(r for r in self.rules if r.chain == "outbound")
        assert outbound.dst_port is None
        assert outbound.protocol == Protocol.ALL

    def test_sg_id_in_tags(self):
        assert any("sg:sg-0abc123" in r.tags for r in self.rules)

    def test_source_field(self):
        assert all(r.source == "aws_sg" for r in self.rules)


# ═══════════════════════════════════════════════════════════════════════════════
# FirewallRule model tests
# ═══════════════════════════════════════════════════════════════════════════════

class TestFirewallRuleModel:

    def test_src_network_cidr(self):
        rule = FirewallRule(
            rule_id="test-01", source="test", priority=0, line_number=1,
            src_ip="192.168.1.0/24", action=Action.ALLOW
        )
        net = rule.src_network()
        import ipaddress
        assert net == ipaddress.ip_network("192.168.1.0/24")

    def test_port_range_single(self):
        rule = FirewallRule(
            rule_id="test-02", source="test", priority=0, line_number=1,
            action=Action.ALLOW
        )
        assert rule.port_range("80") == (80, 80)

    def test_port_range_range(self):
        rule = FirewallRule(
            rule_id="test-03", source="test", priority=0, line_number=1,
            action=Action.ALLOW
        )
        assert rule.port_range("1024:65535") == (1024, 65535)

    def test_port_range_none(self):
        rule = FirewallRule(
            rule_id="test-04", source="test", priority=0, line_number=1,
            action=Action.ALLOW
        )
        assert rule.port_range(None) is None

    def test_to_dict_has_required_keys(self):
        rule = FirewallRule(
            rule_id="test-05", source="test", priority=0, line_number=1,
            action=Action.ALLOW
        )
        d = rule.to_dict()
        for key in ("rule_id", "src_ip", "dst_ip", "protocol", "action", "priority"):
            assert key in d